# Generated by Django 4.0.3 on 2022-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=30)),
                ('turno_manana', models.BooleanField()),
                ('turno_tarde', models.BooleanField()),
                ('turno_noche', models.BooleanField()),
                ('cupos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('clave', models.CharField(max_length=12)),
                ('materia', models.CharField(max_length=30)),
                ('turno_manana', models.BooleanField()),
                ('turno_tarde', models.BooleanField()),
                ('turno_noche', models.BooleanField()),
            ],
        ),
    ]
